name: nm-factory-inf-pip-operation

pool:
  name: Factory-VSS-Agents

#parameters:
#- name: issuer
#  displayName: Issuer Email
#  type: string

#- name: action
#  displayName: Action
#  type: string
#  default: create
#  values:
#  - create
  #- renew WIP
  #- revoke WIP
resources:
  repositories:
  - repository: nm-factory-inf-pip-operations
    type: github
    name: ecl-ado-prj-iac/nm-factory-inf-pip-operations


steps:
- checkout: nm-factory-inf-pip-operations
- task: AzureCLI@2
  displayName: "Backup_gitRepos"
  inputs:
    azureSubscription: 'ecl-az-fact-svc-01-armconnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #!/bin/bash
      ORGANIZATION=https://dev.azure.com/ecl-ado-factory/
      PROJECT=ecl-ado-prj-iac

      echo "List downloaded repositories"
      ls -lat 

      #to be removed
      az extension add --name azure-devops
      az --version
      az account show
      #az config set extension.use_dynamic_install=yes_without_prompt
      echo "Listing repositories ..."
      #az repos list --org $ORGANIZATION --project $PROJECT > /tmp/gitRepo.output
      #echo "Listing repositories ... done"
      #if [ $? -eq 0 ]
      #then
      #  echo "Git repository list:"
      #  jq .[].sshUrl /tmp/gitRepo.output > /tmp/gitRepo.list
      #  cat /tmp/gitRepo.list
      #else
      #  echo "Error fetching the Git repository list"
      #  exit 1
      #fi