name: nm-factory-inf-pip-operation

pool:
  name: Factory-VSS-Agents

schedules:
- cron: "0 2 * * *"
  displayName: Nightly backup
  branches:
    include:
    - main
    - initial
  always: true

#parameters:
#- name: issuer
#  displayName: Issuer Email
#  type: string

#- name: action
#  displayName: Action
#  type: string
#  default: create
#  values:
#  - create
  #- renew WIP
  #- revoke WIP


resources:
  repositories:
  - repository: nm-factory-inf-env-ansible
    type: git
    ecl-ado-prj-iac/nm-factory-inf-env-ansible
  - repository: nm-factory-inf-env-azdevops
    type: git
    ecl-ado-prj-iac/nm-factory-inf-env-azdevops
  - repository: nm-factory-inf-env-dev
    type: git
    ecl-ado-prj-iac/nm-factory-inf-env-dev
  - repository: nm-factory-inf-env-pro
    type: git
    ecl-ado-prj-iac/nm-factory-inf-env-pro
  - repository: nm-factory-inf-env-seed
    type: git
    ecl-ado-prj-iac/nm-factory-inf-env-seed
  - repository: nm-factory-inf-mod-aks
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-aks
  - repository: nm-factory-inf-mod-azdevops
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-azdevops
  - repository: nm-factory-inf-mod-bastion
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-bastion
  - repository: nm-factory-inf-mod-certs
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-certs
  - repository: nm-factory-inf-mod-dns
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-dns
  - repository: nm-factory-inf-mod-fwpolicies
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-fwpolicies
  - repository: nm-factory-inf-mod-keyvault
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-keyvault
  - repository: nm-factory-inf-mod-naming
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-naming
  - repository: nm-factory-inf-mod-network
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-network
  - repository: nm-factory-inf-mod-nsgs
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-nsgs
  - repository: nm-factory-inf-mod-postgresql
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-postgresql
  - repository: nm-factory-inf-mod-routes
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-routes
  - repository: nm-factory-inf-mod-vm
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-vm
  - repository: nm-factory-inf-mod-vpn
    type: git
    ecl-ado-prj-iac/nm-factory-inf-mod-vpn
  - repository: nm-factory-inf-pip-certs
    type: git
    ecl-ado-prj-iac/nm-factory-inf-pip-certs
  - repository: nm-factory-inf-pip-operations
    type: git
    ecl-ado-prj-iac/nm-factory-inf-pip-operations
  - repository: nm-factory-inf-pip-terraform
    type: git
    ecl-ado-prj-iac/nm-factory-inf-pip-terraform
  - repository: nm-factory-k8s-env-helm
    type: git
    ecl-ado-prj-iac/nm-factory-k8s-env-helm
  - repository: nm-factory-k8s-env-helmdev
    type: git
    ecl-ado-prj-iac/nm-factory-k8s-env-helmdev
  - repository: nm-factory-k8s-env-helmdpro
    type: git
    ecl-ado-prj-iac/nm-factory-k8s-env-helmdpro
  - repository: nm-factory-k8s-env-helmdprodev
    type: git
    ecl-ado-prj-iac/nm-factory-k8s-env-helmdprodev
  - repository: nm-factory-k8s-pip-operations
    type: git
    ecl-ado-prj-iac/nm-factory-k8s-pip-operations


jobs:
- job:
  variables:
  - name: BACKUP_FILE
    value: ""
  - name: CONTAINER_FOLDER
    value: "azureGitRepos/backups"
    readonly: true
  - name: ORGANIZATION
    value: "https://dev.azure.com/ecl-ado-factory/"
    readonly: true
  - name: ACCOUNT_NAME
    value: "eclazfactsta01assets"
    readonly: true
  - name: CONTAINER_NAME
    value: "ecl-az-fact-stc-01-backups"
    readonly: true
  - name: RETENTION
    value: "-14 hours" #"-1 days" or "-1 weeks" or "-1 month"
    readonly: true



  steps:
#  - checkout: nm-factory-inf-env-dev
#  - checkout: nm-factory-inf-env-pro
  - script: |
      echo "Clone repositories configured as resources"
      echo "az config"
      az config set extension.use_dynamic_install=yes_without_prompt
      echo "az devops login"
      echo $(System.AccessToken) | az devops login
      echo "az repos list"
      az repos list --organization ${ORGANIZATION} --project ecl-ado-prj-iac | jq .[].remoteUrl | tr -d '"' > /tmp/repoUrls.list

      while read repoUrl; 
      do 
        echo "Cloning $repoUrl"
        git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" --mirror $repoUrl
      done < /tmp/repoUrls.list
      #git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" --mirror "https://ecl-ado-factory@dev.azure.com/ecl-ado-factory/ecl-ado-prj-iac/_git/nm-factory-inf-env-dev"
      ls -lat



  - script: |
      echo "Package backups"
      LOCAL_FOLDER_NAME=`date +%Y%m%d%H%M%S`
      BACKUP_FILE="azureGitRepos-${LOCAL_FOLDER_NAME}.tgz"
      REPO_PREFIX="./nm-factory-*"
      echo "##vso[task.setvariable variable=BACKUP_FILE]${BACKUP_FILE}"
      ls -lat
      mkdir ./${LOCAL_FOLDER_NAME}
      mv ${REPO_PREFIX} ./${LOCAL_FOLDER_NAME}
      tar -cvzf ${BACKUP_FILE} ./${LOCAL_FOLDER_NAME}


  - task: AzureCLI@2
    displayName: "Upload backups"
    inputs:
      azureSubscription: 'ecl-az-fact-svc-01-armconnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        #!/bin/bash
        echo "BACKUP_FILE = ${BACKUP_FILE}"

        ACCOUNT_KEY=$(az storage account keys list --account-name ${ACCOUNT_NAME} --query="[0].value")
        echo "##vso[task.setvariable variable=ACCOUNT_KEY]${ACCOUNT_KEY}"
        az storage account keys list --account-name ${ACCOUNT_NAME} --query="[0].value"
      
        echo "Current Azure account:"
        az account show
        echo "Upload backup file"
        az storage blob upload \
          --account-name ${ACCOUNT_NAME} \
          --account-key ${ACCOUNT_KEY} \
          --container-name ${CONTAINER_NAME} \
          --file ${BACKUP_FILE} \
          --name ${CONTAINER_FOLDER}/${BACKUP_FILE}


  - task: AzureCLI@2
    displayName: "Backup retention"
    inputs:
      azureSubscription: 'ecl-az-fact-svc-01-armconnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |

        thresholdDate=`date -d "${RETENTION}" +%Y%m%d%H%M%S`

        az storage blob list --account-name ${ACCOUNT_NAME} --account-key ${ACCOUNT_KEY} --container-name ${CONTAINER_NAME} --prefix ${CONTAINER_FOLDER}/ | jq .[].name | tr -d "\"" > /tmp/backups.list

        while read line; 
        do 
            fileDate=`basename $line | sed  's/azureGitRepos-//g' | sed 's/.tgz//'`
            echo "Comparison $fileDate -lt $thresholdDate"
            if [ "$fileDate" -lt "$thresholdDate" ]
            then
                echo "Backup cleaning: Removing object $line"
                az storage blob delete --account-name ${ACCOUNT_NAME} --account-key ${ACCOUNT_KEY} --container-name ${CONTAINER_NAME} --name ${line}
            fi
        done < /tmp/backups.list
