trigger: none
pr: none


variables:
- group: factory-dev-keycloak-user-mgmt

parameters:
- name: mail
  displayName: User Email
  type: string
- name: option
  displayName: Group Option
  type: string
  values: 
  - dpro_developer
  - dplt_pipeline
  - dplt_developer
  - infra_admin
  - remove_user

jobs:
- job: ManageUsers
  workspace:
    clean: all
  pool:
    name: Factory-VSS-Agents
  steps:
  - script: |
      chmod +x ./Keycloak/keycloak-user-mgmt-factory-dev.sh

      docker run --entrypoint `pwd`/Keycloak/keycloak-user-mgmt-factory-dev.sh -v `pwd`:`pwd` -w `pwd` -i --rm quay.io/keycloak/keycloak:19.0.3 ${{ parameters.mail}} ${{ parameters.option}} $(password)

      echo "execution finished"