name: nm-factory-inf-pip-operation-maintenance-jenkinsagents-dpl-dev

trigger: none # will disable CI builds entirely
 
pool:
  name: Factory-VSS-Agents

# schedules:
# - cron: "30 2 * * *"
#   displayName: Nightly backup
#   branches:
#     include:
#     - main
#   always: true

# resources:
#   repositories:
#   - repository: nm-factory-dpl-bsp-configuration
#     type: git
#     name: ecl-ado-prj-iac/nm-factory-dpl-bsp-configuration

stages:
- stage: recreate_jenkins_agent_vm 
  jobs:
  - job: recreate_jenkins_agent_vm
    steps:
    - script: |
        echo "Cloning repository"
        echo "az config"
        az config set extension.use_dynamic_install=yes_without_prompt
        echo "Executing ... az devops login"
        echo $(System.AccessToken) | az devops login
        az repos list --organization ${ORGANIZATION} --project ecl-ado-prj-iac | jq .[].remoteUrl | tr -d '"' > /tmp/repoUrls.list

        while read repoUrl; 
        do 
          echo "Cloning $repoUrl"
          git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" --mirror $repoUrl
        done < /tmp/repoUrls.list
        echo "List downloaded repositories"
        ls -lat
      displayName: "Clone repositories"