name: nm-factory-inf-pip-operation-maintenance-dplt-jenkinsagent-recreate

trigger: none # will disable CI builds entirely
 
pool:
  name: Factory-VSS-Agents

schedules:
- cron: "0 1 * * *"
  displayName: Nightly recreate DPLT Jenkins Agent
  branches:
    include:
    - main
  always: true

resources:
  repositories:
  - repository: nm-factory-inf-pip-terraform
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-pip-terraform
  - repository: nm-factory-inf-env-pro
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-env-pro

variables:
- name: azSubscription
  value: ecl-az-fact-svc-01-armconnection
- name: azKeyVaultNameTerraform
  value: ecl-az-seed-kvt-01-tfkv
- name: azTenantId
  value: 9e296acd-1e44-44f0-8c77-cc9dbce85489
        
stages:
- stage: recreate_jenkins_agent_vm 
  jobs:
  - job: recreate_jenkins_agent_vm
    steps:
    - checkout: nm-factory-inf-pip-terraform
    - checkout: nm-factory-inf-env-pro

    - task: AzureKeyVault@2
      displayName: 'Azure Key Vault: ${{ parameters.azKeyVaultNameTerraform }}'
      inputs:
        azureSubscription: ${{ parameters.azSubscription }}
        KeyVaultName: '${{ parameters.azKeyVaultNameTerraform }}'
        SecretsFilter: 'terraform-app-client-id, terraform-app-secret'
        RunAsPreJob: true

    - task: AzureCLI@2
      displayName: "Install TFenv"
      condition: succeeded()
      inputs:
        azureSubscription: ${{ parameters.azSubscription }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/bin/bash
          if [ -f "/usr/local/bin/tfenv" ]; then
            echo "[INFO] TFenv already exists"
          else
            git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
            sudo ln -s ~/.tfenv/bin/* /usr/local/bin
          fi

    - task: AzureCLI@2
      displayName: 'Install SSH Keys'
      inputs:
        azureSubscription: ${{ parameters.azSubscription }}
        scriptType: bash
        scriptPath: '$(System.DefaultWorkingDirectory)/nm-factory-inf-pip-terraform/bash/az_ssh_install.sh'
        
    - task: AzureCLI@2
      displayName: "Recreate DPLT Jenkins Agent" 
      env:
        ARM_CLIENT_ID: $(terraform-app-client-id)
        ARM_CLIENT_SECRET: $(terraform-app-secret)
        ARM_TENANT_ID: ${{ parameters.azTenantId }}'  #Must move to KeyValut or inside provider.tf
      inputs:
        azureSubscription: ${{ parameters.azSubscription }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/bin/bash

          set -o errexit  # Exit on error
          set -o nounset  # Exit on uninitalized vars
          set -o pipefail # Exit on pipe exec fail

          cd $(System.DefaultWorkingDirectory)/nm-factory-inf-env-pro/200-jenkins-agent-vm-dplt
          echo "terraform init"
          terraform init
          echo "terraform plan --replace=module.virtual_machine.azurerm_linux_virtual_machine.main"
          terraform plan --replace=module.virtual_machine.azurerm_linux_virtual_machine.main