name: nm-factory-inf-pip-operation-start-akstest

pool:
  name: Factory-VSS-Agents

variables:
- group: factory-azure-mgmt

schedules:
- cron: "40 * * * *"
  displayName: Starting the AKStest cluster
  branches:
    include:
    - main
  always: true

stages:
- stage: Start_AKStest_cluster
  jobs:
  - job: start_akstest_cluster

    steps:
    - task: AzureCLI@2
      displayName: "Start AKStest cluster" 
      env:
        ARM_CLIENT_ID: $(terraform-app-client-id)
        ARM_CLIENT_SECRET: $(terraform-app-secret)
        ARM_TENANT_ID: "9e296acd-1e44-44f0-8c77-cc9dbce85489"  #Must move to KeyVault or inside provider.tf
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Start AKStest Cluster"
          az aks start --name ecl-az-fact-cls-01-akstest --resource-group tes-te-test-tes-01-test --subscription azure-euroctl-hub-subs