name: nm-factory-inf-pip-operation-maintenance-jenkinsagents-dpl-dev

trigger: none # will disable CI builds entirely
 
pool:
  name: Factory-VSS-Agents

# schedules:
# - cron: "30 2 * * *"
#   displayName: Nightly backup
#   branches:
#     include:
#     - main
#   always: true

resources:
  repositories:
  - repository: nm-factory-inf-env-dev
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-env-dev
  - repository: nm-factory-inf-env-dev
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-naming

stages:
- stage: recreate_jenkins_agent_vm 
  jobs:
  - job: recreate_jenkins_agent_vm
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform 1.3.0'
      inputs:
        terraformVersion: 1.3.0

    - script: |
        echo "Cloning repository"
        echo "az config"
        az config set extension.use_dynamic_install=yes_without_prompt
        echo "Executing ... az devops login"
        echo $(System.AccessToken) | az devops login
        git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" https://ecl-ado-factory@dev.azure.com/ecl-ado-factory/ecl-ado-prj-iac/_git/nm-factory-inf-env-dev
        ls -lat
      displayName: "Clone repository"
    
    - task: AzureCLI@2
      displayName: "Install SSH keys"
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/bin/bash

          set -o errexit  # Exit on error
          set -o nounset  # Exit on uninitalized vars
          set -o pipefail # Exit on pipe exec fail

          VAULT_NAME="ecl-az-fact-kvt-01-main"

          [ -d ~/.ssh ] || mkdir ~/.ssh
          [ -f ~/.ssh/id_rsa ] || az keyvault secret download --name poc-prv-key --vault-name ${VAULT_NAME} --file ~/.ssh/id_rsa
          [ -f ~/.ssh/id_rsa.pub ] || az keyvault secret download --name poc-pub-key --vault-name ${VAULT_NAME} --file ~/.ssh/id_rsa.pub
          [ -f ~/.ssh/known_hosts ] || az keyvault secret download --name poc-keyscan --vault-name ${VAULT_NAME} --file ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          export ARM_TENANT_ID="9e296acd-1e44-44f0-8c77-cc9dbce85489"
          export ARM_CLIENT_SECRET=$(az keyvault secret download --name terraform-app-secret --vault-name ecl-az-seed-kvt-01-tfkv)
          export ARM_CLIENT_ID=$(az keyvault secret download --name terraform-app-client-id --vault-name ecl-az-seed-kvt-01-tfkv)
    - script: |
        cd nm-factory-inf-env-dev/200-jenkins-agent-dplt-dev
        ls -lat
        pwd
        echo "terraform init"
        terraform init
        echo "terraform plan"
        terraform plan
      displayName: "Run Terraform"      