name: nm-factory-inf-pip-operation-maintenance-jenkinsagents-dpl-dev

trigger: none # will disable CI builds entirely
 
pool:
  name: Factory-VSS-Agents

# schedules:
# - cron: "30 2 * * *"
#   displayName: Nightly backup
#   branches:
#     include:
#     - main
#   always: true

# resources:
#   repositories:
#   - repository: nm-factory-dpl-bsp-configuration
#     type: git
#     name: ecl-ado-prj-iac/nm-factory-dpl-bsp-configuration

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build_api
    displayName: Build API
    steps:
      - template: ./build-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/api'

stages:
- stage: Recreate Jenkins Agent VM 
  jobs:
  - job: Recreate Jenkins Agent VM
    steps:
      - task: Clone nm-factory-inf-env-dev repository
        displayName: 'Cloning git repository'
        inputs:
          script: |
            echo 'Cloning into sources folder at: $(Build.SourcesDirectory)'
            git clone https://ecl-ado-factory@dev.azure.com/ecl-ado-factory/ecl-ado-prj-iac/_git/nm-factory-inf-env-dev
            exit