name: nm-factory-inf-pip-operation-maintenance-dplt-jenkinsagent-recreate

trigger: none # will disable CI builds entirely
 
pool:
  name: Factory-VSS-Agents

schedules:
- cron: "0 1 * * *"
  displayName: Nightly recreate DPLT Jenkins Agent
  branches:
    include:
    - main
  always: true

variables:
- name: TF_REPOSITORY
  value: "https://ecl-ado-factory@dev.azure.com/ecl-ado-factory/ecl-ado-prj-iac/_git/nm-factory-inf-env-pro"

resources:
  repositories:
  - repository: nm-factory-inf-env-pro
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-env-pro

stages:
- stage: recreate_jenkins_agent_vm 
  jobs:
  - job: recreate_jenkins_agent_vm
    steps:
    - task: AzureKeyVault@2
      displayName: 'Azure Key Vault: ecl-az-seed-kvt-01-tfkv'
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        KeyVaultName: 'ecl-az-seed-kvt-01-tfkv'
        SecretsFilter: 'terraform-app-client-id, terraform-app-secret'
        RunAsPreJob: true

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform 1.3.0'
      inputs:
        terraformVersion: 1.3.0

    - checkout: nm-factory-inf-env-pro
        
    - task: AzureCLI@2
      displayName: "Recreate DPLT Jenkins Agent" 
      env:
        ARM_CLIENT_ID: $(terraform-app-client-id)
        ARM_CLIENT_SECRET: $(terraform-app-secret)
        ARM_TENANT_ID: "9e296acd-1e44-44f0-8c77-cc9dbce85489"  #Must move to KeyValut or inside provider.tf
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/bin/bash

          set -o errexit  # Exit on error
          set -o nounset  # Exit on uninitalized vars
          set -o pipefail # Exit on pipe exec fail

          cd $(System.DefaultWorkingDirectory)
          ls -lrtha

          cd $(System.DefaultWorkingDirectory)/.git/
          ls -lrtha

          cd $(System.DefaultWorkingDirectory)/200-jenkins-agent-dplt
          echo "terraform init"
          terraform init
          echo "terraform plan --replace=azurerm_linux_virtual_machine_scale_set.jenkins-agent"
          terraform plan --replace=azurerm_linux_virtual_machine_scale_set.jenkins-agent