name: Start-aksdev

pool:
  name: Factory-VSS-Agents

trigger: none

schedules:
- cron: "30 5 * * 1-5"
  displayName: Starting the AKStest cluster
  branches:
    include:
    - main
  always: true

stages:
- stage: Start_AKSdev_cluster
  jobs:
  - job: start_aksdev_cluster

    steps:
    - task: AzureCLI@2
      displayName: "Start AKSdev cluster" 
      env:
        ARM_CLIENT_ID: $(terraform-app-client-id)
        ARM_CLIENT_SECRET: $(terraform-app-secret)
        ARM_TENANT_ID: $(tenant)
      inputs:
        azureSubscription: '<subscription>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Start AKSdev Cluster"
          az aks start --name <aksdev> --resource-group <resource_group> --subscription <subscription>