name: Stop-aksdev

pool:
  name: Factory-VSS-Agents

trigger: none

schedules:
- cron: "00 17 * * 1-5"
  displayName: Stopping the AKStest cluster
  branches:
    include:
    - main
  always: true

stages:
- stage: Stop_AKSdev_cluster
  jobs:
  - job: stop_aksdev_cluster

    steps:
    - task: AzureCLI@2
      displayName: "Stop AKSdev cluster" 
      env:
        ARM_CLIENT_ID: $(terraform-app-client-id)
        ARM_CLIENT_SECRET: $(terraform-app-secret)
        ARM_TENANT_ID: $(tenant)
      inputs:
        azureSubscription: '<subscription>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Stop AKSdev Cluster"
          az aks stop --name <aksdev> --resource-group <resource_group> --subscription <subscription>