name: nm-factory-inf-pip-operation-backup-repos-inf-mod

pool:
  name: Factory-VSS-Agents

schedules:
- cron: "0 2 * * *"
  displayName: Nightly backup
  branches:
    include:
    - main
    - initial
  always: true

resources:
  repositories:
  - repository: nm-factory-inf-mod-aks
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-aks
  - repository: nm-factory-inf-mod-azdevops
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-azdevops
  - repository: nm-factory-inf-mod-bastion
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-bastion
  - repository: nm-factory-inf-mod-certs
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-certs
  - repository: nm-factory-inf-mod-dns
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-dns
  - repository: nm-factory-inf-mod-fwpolicies
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-fwpolicies
  - repository: nm-factory-inf-mod-keyvault
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-keyvault
  - repository: nm-factory-inf-mod-naming
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-naming
  - repository: nm-factory-inf-mod-network
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-network
  - repository: nm-factory-inf-mod-nsgs
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-nsgs
  - repository: nm-factory-inf-mod-postgresql
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-postgresql
  - repository: nm-factory-inf-mod-routes
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-routes
  - repository: nm-factory-inf-mod-vm
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-vm
  - repository: nm-factory-inf-mod-vpn
    type: git
    name: ecl-ado-prj-iac/nm-factory-inf-mod-vpn


jobs:
- template: azure-pipelines.yml