name: nm-factory-inf-pip-operation-okta-dpro-user-mgmt

trigger: none # will disable CI builds entirely
 
pool:
  name: Factory-VSS-Agents

parameters:
- name: firstName
  displayName: First Name
  type: string

- name: lastName
  displayName: Last Name
  type: string

- name: email
  displayName: Email
  type: string

- name: dproGroup
  displayName: Okta DPRO Group
  type: string
  values:
    - Openshift_Factory_1C,3C,4C_developer
    - Openshift_Factory_1C,3C,4C_PGadmin
    - Openshift_Factory_1C,3C,4C_operator
    - Openshift_Factory_2C
    - ECTL_Openshift_2C,4C,8C,9C,10C,11C,14C_developer
    - ECTL_Openshift_2C,4C,8C,9C,10C,11C,14C_PGadmin    
    - ECTL_Openshift_14C_operator

- name: option
  displayName: Option
  type: string
  values:
    - create_user
    - update_user
    - delete_user

variables:
- name: oktaDomain
  value: "iam-nm-dev-dpro-admin.okta.com"

stages:
- stage: okta_user_management
  jobs:
  - job: create_okta_user
    condition: ${{ eq(parameters.option, 'create_user') }}
    steps:
    - task: AzureKeyVault@2
      displayName: 'Azure Key Vault: ecl-az-fact-kvt-01-main'
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        KeyVaultName: 'ecl-az-fact-kvt-01-main'
        SecretsFilter: 'okta-token'
        RunAsPreJob: true                

    - task: Bash@3
      displayName: 'Creation of the user'
      inputs:
        targetType: 'inline'
        script: |
          echo "Creating user and sending activation mail"
          curl --no-progress-meter -w '{"http_code": "%{http_code}"}' -X POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: SSWS ${OKTA_TOKEN}" \
          -d '{
            "profile": {
              "firstName": "'"${{parameters.firstName}}"'",
              "lastName": "'"${{parameters.lastName}}"'",
              "email": "'"${{parameters.email}}"'",
              "login": "'"${{parameters.email}}"'"
            }
          }' "https://${{variables.oktaDomain}}/api/v1/users?activate=true" | jq -s '.[-1] * .[-2]' | jq "{ http_code: .http_code, id: .id, status: .status, profile: .profile, errorSummary: .errorSummary, errorCauses: .errorCauses }" > resp.json
          cat resp.json
          http_code=$(jq .http_code resp.json | tr -d '"') 
          if [[ $http_code -ge 400 ]]; then
            echo "Operation Failed, the user has not been created"
            exit -1
          else
            echo "User created successfully"
          fi

      env:
        OKTA_TOKEN: $(okta-token)

  - job: adding_user_to_groups
    condition: not( ${{ eq(parameters.option, 'delete_user') }} )
    dependsOn: create_okta_user
    steps:
    - task: AzureKeyVault@2
      displayName: 'Azure Key Vault: ecl-az-fact-kvt-01-main'
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        KeyVaultName: 'ecl-az-fact-kvt-01-main'
        SecretsFilter: 'okta-token'
        RunAsPreJob: true     

    - task: Bash@3
      displayName: 'Adding user to groups'
      inputs:
        targetType: 'inline'
        script: |   
          echo "Create variable with all groups needed"
          if [[ ${{parameters.dproGroup}} == "Openshift_Factory_1C,3C,4C_developer" ]]; then
             list_group=("dprodev1c_dplt_developer"               "dprodev3c_dplt_developer"                 "dprodev4c_dplt_developer")
          elif [[ ${{parameters.dproGroup}} == "Openshift_Factory_1C,3C,4C_PGadmin" ]]; then
             list_group=("dprodev1c_dplt_administrator"               "dprodev3c_dplt_administrator"                 "dprodev4c_dplt_administrator")
          elif [[ ${{parameters.dproGroup}} == "Openshift_Factory_1C,3C,4C_operator" ]]; then
             list_group=("dprodev1c_dplt_operator"               "dprodev3c_dplt_operator"                 "dprodev4c_dplt_operator")
          elif [[ ${{parameters.dproGroup}} == "Openshift_Factory_2C" ]]; then
             list_group=("dprodev2c_dplt_administrator"               "dprodev2c_dplt_developer")
          elif [[ ${{parameters.dproGroup}} == "ECTL_Openshift_2C,4C,8C,9C,10C,11C,14C_developer" ]]; then
             list_group=("nmdevtst2c_dplt_developer"               "nmdevtst4c_dplt_developer"                 "nmdevtst8c_dplt_developer"                 "nmdevtst10c_dplt_developer"                 "nmdevtst11c_dplt_developer"                 "nmdevtst14c_dplt_developer")                               
          elif [[ ${{parameters.dproGroup}} == "ECTL_Openshift_2C,4C,8C,9C,10C,11C,14C_PGadmin" ]]; then
             list_group=("nmdevtst2c_dplt_administrator"               "nmdevtst4c_dplt_administrator"                 "nmdevtst8c_dplt_administrator"                 "nmdevtst10c_dplt_administrator"               "nmdevtst11c_dplt_administrator"               "nmdevtst14c_dplt_administrator")                               
          elif [[ ${{parameters.dproGroup}} == "ECTL_Openshift_14C_operator" ]]; then
             list_group=("nmdevtst14c_dplt_operator")                               
          else
             echo "Bad dpro group option"
             exit -1
          fi

          echo "Get group ids from all the groups at which the user will be added"
          for i in ${!list_group[@]}; do
            listid_group[$i]=$(curl -XGET \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: SSWS ${OKTA_TOKEN}" \
            "https://${{variables.oktaDomain}}/api/v1/groups?search=profile.name+eq+%22${list_group[$i]}%22" | jq -r '.[].id')
          done

          echo "Get the user ID"
          userId=$(curl -X GET \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: SSWS ${OKTA_TOKEN}" \
          "https://${{variables.oktaDomain}}/api/v1/users?search=profile.email+eq+%22${{parameters.email}}%22" | jq -r '.[].id')    

          echo "Adding the user to the groups"
          for i in ${!listid_group[@]}; do
            curl --no-progress-meter -w '{"http_code": "%{http_code}"}' -X PUT \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: SSWS ${OKTA_TOKEN}" \
            "https://${{variables.oktaDomain}}/api/v1/groups/${listid_group[$i]}/users/$userId" | jq -r '.http_code' > http_code
            if [[ $http_code -ge 400 ]]; then
              echo "User has not been added to ${list_group[$i]} group"
              exit -1
            else
              echo "User successfully added to ${list_group[$i]} group"
            fi
          done
      env:
        OKTA_TOKEN: $(okta-token)          

  - job: delete_okta_user
    condition: ${{ eq(parameters.option, 'delete_user') }}
    steps:
    - task: AzureKeyVault@2
      displayName: 'Azure Key Vault: ecl-az-fact-kvt-01-main'
      inputs:
        azureSubscription: 'ecl-az-fact-svc-01-armconnection'
        KeyVaultName: 'ecl-az-fact-kvt-01-main'
        SecretsFilter: 'okta-token'
        RunAsPreJob: true     

    - task: Bash@3
      displayName: 'Deleting user'
      inputs:
        targetType: 'inline'
        script: |
          echo "Getting user id for ${{parameters.email}}."
          userId=$(curl -X GET \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: SSWS ${OKTA_TOKEN}" \
          "https://${{variables.oktaDomain}}/api/v1/users?search=profile.email+sw+%22${{parameters.email}}%22" | jq -r '.[].id')
          if [[ -z userId ]]; then
            echo "User does not exist"
            exit -1
          else
            echo "User successfully loaded"
          fi

          echo "Deactivating the user before deleting it"
          curl --no-progress-meter -w '{"http_code": "%{http_code}"}' -X POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: SSWS ${OKTA_TOKEN}" \
          "https://${{variables.oktaDomain}}/api/v1/users/$userId/lifecycle/deactivate?sendEmail=false" | jq -s '.[-1] * .[-2]' | jq "{ http_code: .http_code, id: .id, status: .status, profile: .profile, errorSummary: .errorSummary, errorCauses: .errorCauses }" > resp.json

          http_code=$(jq .http_code resp.json | tr -d '"') 
          if [[ $http_code -ge 400 ]]; then
            echo "Operation Failed, the user has not been deactivated"
            exit -1
          else
            echo "User deactivated successfully"
          fi

          echo "Deleting the user"
          curl --no-progress-meter -w '{"http_code": "%{http_code}"}' -X DELETE \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: SSWS ${OKTA_TOKEN}" \
          "https://${{variables.oktaDomain}}/api/v1/users/$userId?sendEmail=false" | jq -s '.[-1] * .[-2]' | jq "{ http_code: .http_code, id: .id, status: .status, profile: .profile, errorSummary: .errorSummary, errorCauses: .errorCauses }" > resp.json
          http_code=$(jq .http_code resp.json | tr -d '"') 
          if [[ $http_code -ge 400 ]]; then
            echo "Operation Failed, the user has not been deleted"
            exit -1
          else
            echo "User deleted successfully"
          fi
      env:
        OKTA_TOKEN: $(okta-token)